name: Close Issue on Command

on:
  issue_comment:
    types: [created, edited]

jobs:
  closeIssue:
    name: Comment Job
    runs-on: ubuntu-latest
    steps:
    - name: Check if comment contains "/close"
      uses: actions/github-script@v6
      with:
        script: |
          if (context.payload.comment.body.includes('/close')) {
            console.log('Closing the issue...');
          github.rest.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed'
          });
          } else {
            console.log('No "/close" command found. The issue will remain open.');
          }