name: Close Issue on Command

on:
  issue_comment:
    types: [created]

jobs:
  closeIssue:
    name: Comment Job
    runs-on: ubuntu-latest
    steps:
    - name: Install @octokit/rest
      run: npm install @octokit/rest@latest

    - name: Install node-fetch
      run: npm install node-fetch@latest

    - name: Check if comment contains "/close"
      uses: actions/github-script@v6
      with:
        script: |
          const { Octokit } = require("@octokit/rest");
          const fetch = require("node-fetch"); // Import the node-fetch package
          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN,
            request: {
              fetch, 
            },
          });

          if (context.payload.comment.body.includes('/close')) {
            console.log('Closing the issue...');
            const issue_number = context.payload.issue.number;
            const { owner, repo } = context.repo;

            octokit.issues.update({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              state: 'closed'
            });
          } else {
            console.log('No "/close" command found. The issue will remain open.');
          }